name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to run'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

permissions:
  contents: read

env:
  AWS_REGION: eu-central-1
  TF_IN_AUTOMATION: true
  TF_INPUT: false
  TF_VAR_hub_vpc_id: ${{ secrets.HUB_VPC_ID }}
  TF_VAR_web_ami_id: ${{ secrets.WEB_AMI_ID }}
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
  TF_VAR_hub_route_priv_table_id: ${{ secrets.RT_HUB_PRIV}}

jobs:
  plan:
    name: Terraform plan
    if: github.event_name != 'workflow_dispatch' || inputs.action == 'apply'
    runs-on: [self-hosted, Linux, ARM64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform format check
        run: terraform fmt -check -recursive

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -input=false -out=tfplan

      - name: Upload Terraform plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan
          retention-days: 1

  apply:
    name: Terraform apply
    if: github.event_name == 'workflow_dispatch' && inputs.action == 'apply'
    needs: plan
    runs-on: [self-hosted, Linux, ARM64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init -input=false

      - name: Download Terraform plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan

      - name: Terraform apply
        run: terraform apply -input=false tfplan

  destroy:
    name: Terraform destroy
    if: github.event_name == 'workflow_dispatch' && inputs.action == 'destroy'
    runs-on: [self-hosted, Linux, ARM64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform destroy
        run: terraform destroy -input=false -auto-approve